config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "dashboard", to: "dashboards#show"
  resources :rooms, except: %i[edit destroy] do
    resources :messages, only: :create
  end

  resources :users, only: :show do
    resources :appointments, only: %i[update]
  end

  resources :appointments, only: %i[create update]
  resources :chatrooms, only: :show

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_about-homepage.html.erb
<div data-aboutpage-target="about" class="about-container">
  <div class="d-flex justify-content-center mb-5"><h1 class="trami-font font-65 color-black-gray pt-5">All about</h1>&nbsp&nbsp<h1 class="trami-font font-120 orange">Trami</h1></div>
  <div class="d-flex justify-content-center mb-5">
    <div class="line"></div>&nbsp&nbsp<h5 class="trami-font color-black-gray font-48">How it works?</h5>&nbsp&nbsp<div class="line"></div>
  </div>
  <div class="container-insruction d-flex justify-content-around">
    <div class="block-instruction">
      <div class="icon-instruction">
        <%= image_tag("discover.png", alt: "discover-img", class: "discover-img") %>
      </div>
      <p class="main-font weight-300 font-18 text-black-gray pt-5">Discover events and activities. Whether it is nearby location or in worldwide.</p>
    </div>
    <div class="block-instruction">
      <div class="icon-instruction">
        <%= image_tag("calendar.png", alt: "calendar-img", class: "calendar-img grayscale contrast brightness") %>
      </div>
      <p class="main-font weight-300 font-18 text-black-gray pt-5">Create your own Trami group for specific date and location.</p>
    </div>
    <div class="block-instruction">
      <div class="icon-instruction">
        <%= image_tag("reward.png", alt: "reward-img", class: "reward-img grayscale contrast brightness") %>
      </div>
      <p class="main-font weight-300 font-18 text-black-gray pt-5">Become Trami expert through every event’s experience.</p>
    </div>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div class="carousel-container">
  <div class="d-flex flex-column align-items-start city-container">
    <div class="city-info">
      <h1 id="header-font" class="trami-font text-black-gray pb-5 font-65">Featured cities</h1>
      <h5 class="main-font weight-300 text-black-gray">Looking for fun things to do near you? See what events happening in cities around the country.</h5>
    </div>
  </div>
    <!-- Swiper -->
  <div class="swiper-container">
    <div class="swiper swiper-1 mySwiper mb-0 swiper-box" data-controller="swiper">
      <div class="swiper-wrapper swiper-wrapper-1">
        <div class="swiper-slide swiper-slide-1">
          <%= image_tag "Berlin.png" %>
        </div>
        <div class="swiper-slide swiper-slide-1">
          <%= image_tag "London.png" %>
        </div>
        <div class="swiper-slide swiper-slide-1">
          <%= image_tag "Sydney.png" %>
        </div>
        <div class="swiper-slide swiper-slide-1">
          <%= image_tag "Paris.png" %>
        </div>
        <div class="swiper-slide swiper-slide-1">
          <%= image_tag "SF.png" %>
        </div>
        <div class="swiper-slide swiper-slide-1">
          <%= image_tag "Moscow.png" %>
        </div>
      </div>
      <div class="swiper-pagination"></div>
    </div>
  </div>

  <div class="d-flex justify-content-center create-room-container">
    <div class="create-room d-flex align-items-center mx-5">
      <h5 class="main-font mb-0 me-4 weight-300 text-black-gray">Create your own Trami room</h5>

      <%= link_to "Get started", new_user_session_path, class: "start-button button-content weight-300 my-3" %>

    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="container-f pt-2 footer">
  <div class="d-flex justify-content-between align-items-center py-2" id="footer-container">
    <p class="mb-2">© 2024 Trami</p>
    <p class="mb-2">Made by Trami — Jerry, Thu, Julien, Bhawana</p>
  </div>
</div>

app/views/shared/_main-homepage.html.erb
<div class="main-container">
  <div class="wrap d-flex justify-content-around">
    <div class="tag-line">
      <h1 class="trami-font font-65 text-black-gray">When every Journey</h1>
      <div class="d-flex">
        <h1 class="trami-font font-65 orange">sparks</h1>&nbsp&nbsp<h1 class="trami-font font-65 text-black-gray">a Friendship</h1>
      </div>
      <h5 data-action="click->aboutpage#toggle" class="about main-font weight-300 text-black-gray pt-2">Know more about Trami Community →</h5>
    </div>
    <div class="image">
      <%= image_tag("trami-img.png", alt: "trami-img", class: "trami-img") %>
      <%= image_tag("trami-img.png", alt: "trami-img", class: "trami-img trami-img-2") %>
    </div>
  </div>
  <div class="search-wrap">
    <h5 class="main-font weight-300 text-brown pb-2">Your Weekend or Holiday activities are just a search away</h5>
    <div class="search-bar mt-2">
      <%= form_with url: rooms_path, method: :get do |f| %>
        <%= f.text_field :address, placeholder: "location", class: "location main-font" %>
        <%= f.text_field :date, data: { controller: "flatpickr" }, placeholder: "from - to", class: "date date-1 main-font"%>
        <%= f.submit "search", class: "search-btn main-font" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm d-flex justify-content-between">
    <div class="d-flex align-items-center trami-div">
      <h1 class="font-48"><%= link_to "Trami", root_path, class: "trami-font font-logo" %></h1>
    </div>
    <div class="navbar-nav nav-style d-flex justify-content-end" style = "width:100%" >
      <% if user_signed_in? %>
        <div class="nav-item d-flex justify-content-between" id="log-out">
          <div class="d-flex align-items-center">
            <%= link_to "Explore", rooms_path, class: "explore-nav-btn px-3 weight-300" %>
          </div>
          <div class="d-flex align-items-center">
              <%= link_to "Dashboard", dashboard_path, class: "dashboard-btn px-3 weight-300" %>
          </div>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "link-secondary smooth nav-link" %>
        </div>
      </div>
      <% else %>
      <div class="navbar-nav nav-style d-flex justify-content-between" style = "width:65%">
        <div class ="navbar-header-text d-flex align-items-center">
            <p class="main-font weight-300">Sign up with us and ready to board ✈️</p>
        </div>
        <div class="nav-item d-flex align-items-center">
          <div class="d-flex ms-auto align-items:end justify-content-end">
            <div class="d-flex align-items-center">
              <%= link_to "Sign up",new_user_registration_path, data: { turbo: false }, class: "signup-btn px-3 weight-300" %>
            </div>
            <%= link_to "Login", new_user_session_path, class: "login-btn weight-300" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>

app/views/shared/_newindex.html.erb
<div class="container" style=" background-image: linear-gradient(rgba(0, 0, 0, .1) .1em, transparent .1em), linear-gradient(90deg, rgba(0, 0, 0, .1) .1em, transparent .1em);
  background-size: 2em 2em;" >

  <%# All Room card swiper display %>
  <div>
    <h1>Avalibe Rooms for you.</h1>
  </div>
  <div class="row" >
      <%= render 'roomcard' %>
  </div>
  <br><br>
  <div class= "map d-flex">
  <div class="col-12">
    <%# Map display code %>
  <br><h1>Search yor place here.</h1><br>
  <div style="width: 100%; height: 600px; z-index: 100"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>
</div>
</div>

app/views/shared/_newroomcard.html.erb
<div class="swiper roomcardSwiper d-flex justify-content-center" data-controller="roomcard-swiper">
  <div class="swiper-wrapper">
    <% @rooms.each do |room| %>
      <div class="swiper-slid room-slide">
        <%= link_to room_path(room), class: "text-decoration-none" do %>
          <div class="d-flex justify-content-center">
            <div class="card-body room-slide-card d-flex" style="background-color: <%= room.activity.mood.color%>">
              <div class= "card-header col"><h3><%= room.title %></h3></div>
              <br>
              <div class= "card-description"><h3><%=room.description.capitalize %></h3></div>
              <div class="row room-info-banner">
                <div class ="col-6" > Age: <%= room.min_age %> - <%= room.max_age %></div>
                <div class ="col-6" > 🗓️ <%= room.date.strftime('%d %b %y') %></div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</div>

app/views/shared/_ques.html.erb
<div class="questionaire-container">
  <div class="trami-bg d-flex flex-column align-items-center">
    <h1 class="ques-welcome text-black-gray">Hi&nbsp Friend,</h1>
    <div class="div-transparent">
      <div id="carouselExampleCaptions" class="carousel slide">
        <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active d-none" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" class="d-none" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" class="d-none" aria-label="Slide 3"></button>
      </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="ques-mood carousel-content">
              <div class="question-1 text-center">
                <h1 class="main-font weight-300 font-30 text-black-gray">What's your mood?</h1>
              </div>
              <div class="mood-card-wrap d-flex flex-column align-items-center">
                <div class="mood-card-1 d-flex">
                  <div class="pt-2 mood-card-dreamy mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Dreamy</p>
                  </div>
                  <div class="pt-2 mood-card-energetic mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Energetic</p>
                  </div>
                  <div class="pt-2 mood-card-relax mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Relax</p>
                  </div>
                  <div class="pt-2 mood-card-neutral mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Neutral</p>
                  </div>
                  <div class="pt-2 mood-card-social mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Social</p>
                  </div>
                  <div class="pt-2 mood-card-competitive mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Competitive</p>
                  </div>
                </div>
                <div class="mood-card-2 d-flex">
                  <div class="pt-2 mood-card-adventurous mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Adventurous</p>
                  </div>
                  <div class="pt-2 mood-card-chllin mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Chillin</p>
                  </div>
                  <div class="pt-2 mood-card-creative mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Creative</p>
                  </div>
                  <div class="pt-2 mood-card-intellectual mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Intellectual</p>
                  </div>
                  <div class="pt-2 mood-card-exploratory mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Exploratory</p>
                  </div>
                  <div class="pt-2 mood-card-mindful mood-card d-flex justify-content-center flex-column align-items-center">
                    <p class="main-font text-black-gray">Mindful</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="ques-location carousel-content">
              <div class="text-center d-flex flex-column align-items-center">
                <div class="question-2">
                  <h1 class="main-font weight-300 font-30 text-black-gray">Where's your current location?</h1>
                </div>
                <div class="location-bar">
                  <%= form_with url: rooms_path, method: :get, class: "location-form" do |f| %>
                  <%= f.select :user, collection: User.all.pluck(:address), class: "city-location main-font" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="ques-status carousel-content">
              <div class="d-flex flex-column align-items-center">
                <h5 class="main-font weight-300 font-18 text-black-gray mt-2">Last step...</h5>
                <div>
                  <div class="question-3 text-center">
                    <h1 class="main-font weight-300 font-30 text-black-gray">Please select who you are?</h1>
                  </div>
                  <div class="ques-3-choice d-flex justify-content-around">
                    <div class="status-container d-flex flex-column align-items-center">
                      <h1 class="mb-3 ques-3-icon">⛺️</h1>
                      <div class="ques-3-ans">
                        <h5 class="mx-3 main-font weight-300 font-18 text-black-gray mb-0">I'm a local</h5>
                      </div>
                    </div>
                    <div class="or-text d-flex justify-content-center pt-5">
                      <h5 class="weight-300 main-font text-black-gray font-18">or</h5>
                    </div>
                    <div class="status-container d-flex flex-column align-items-center">
                      <h1 class="mb-3 ques-3-icon">🚀</h1>
                      <div class="ques-3-ans">
                        <h5 class="mx-1 main-font weight-300 font-18 text-black-gray mb-0">I'm a traveller</h5>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon round-button trami-font" aria-hidden="true">→</span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_questionaire-page.html.erb
<div class="questionaire-container">
  <div class="trami-img-bg"></div>
  <div class="d-flex flex-column align-items-center">
    <h1 data-controller="wave" class="elementToFadeInAndOut ques-welcome text-black-gray"></h1>
    <div class="div-transparent">
      <%= form_with url: rooms_path, method: :get do |f| %>
        <div data-controller="last-slide" id="carouselExampleCaptions" class="fadein-3 mt-5 carousel carousel-1 slide">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active d-none" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" class="d-none" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" class="d-none" aria-label="Slide 3"></button>
          </div>
          <div data-controller="last-slide" class="carousel-inner carousel-inner-1">
            <div class="carousel-item active">
              <div class="mt-2 carousel-content carousel-content-1">
                <div class="question-1 text-center">
                  <h1 class="main-font weight-300 font-30 text-black-gray">What's your mood?</h1>
                </div>
                <div data-controller="questionaires questionaires-status" class="mood-card-wrap d-flex flex-column align-items-center">
                  <div class="mood-card-1 d-flex">
                    <div id="Dreamy" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood" class="mood-card-dreamy mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.first.name.capitalize, value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                    <div id="Energetic" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood" class="mood-card-energetic mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.second.name.capitalize, value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                    <div id="Relax" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood" class="pt-2 mood-card-relax mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.third.name.capitalize, for:"relax", value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                    <div id="Neutral" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood" class="pt-2 mood-card-neutral mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.fourth.name.capitalize, value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                    <div id="Social" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood" class="pt-2 mood-card-social mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.fifth.name.capitalize, value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                    <div id="Competitive" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood" class="pt-2 mood-card-competitive mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.all[5].name.capitalize, value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                  </div>
                  <div class="mood-card-2 mt-4 d-flex">
                    <div id="Adventurous" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood"class="pt-2 mood-card-adventurous mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.all[6].name.capitalize, value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                    <div id="Chillin" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood" class="pt-2 mood-card-chillin mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.all[7].name.capitalize, value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                    <div id="Creative" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood" class="pt-2 mood-card-creative mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.all[8].name.capitalize, value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                    <div id="Intellectual" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood" class="pt-2 mood-card-intellectual mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.all[9].name.capitalize, value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                    <div id="Exploratory" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood" class="pt-2 mood-card-exploratory mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.all[10].name.capitalize, value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                    <div id="Mindful" data-questionaires-target="moodElement" data-action="click->questionaires#mood click->questionaires-status#removeMood" class="pt-2 mood-card-mindful mood-card d-flex justify-content-center flex-column align-items-center">
                      <%= f.label :mood, Mood.all[11].name.capitalize, value: params[:mood], class: "main-font text-black-gray" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="carousel-item">
              <div class="ques-location mt-3 d-flex flex-column align-items-end carousel-content carousel-content-1">
                <div class="mt-3 mb-5 text-center d-flex justify-content-center align-items-center">
                  <div class="question-2">
                    <h1 class="main-font weight-300 mb-0 mx-5 font-28 text-black-gray">Where's your current location?</h1>
                  </div>
                  <div class="location-bar d-flex justify-content-center align-items-center">
                    <%= f.select :address, @cities, value: params[:address], class: "city-location main-font" %>
                  </div>
                </div>
                <div class="d-flex mt-5 justify-content-center align-items-center">
                  <h1 class="main-font mb-0 mx-5 weight-300 font-28 text-black-gray">When do you want to go out?</h1>
                  <div class="date-input d-flex justify-content-center align-items-center"><%= f.text_field :date, data: { controller: "flatpickr" }, placeholder: "from - to", class: "date date-location main-font"%></div>
                </div>
              </div>
            </div>
            <div id="last" data-action="click->last-slide#fired" class="carousel-item last-slide">
              <div class="ques-status carousel-content carousel-content-1">
                <div class="mt-2 d-flex flex-column align-items-center">
                  <h5 class="main-font weight-300 font-18 text-black-gray mt-2">Last step...</h5>
                  <div class="question-3 text-center">
                    <h1 class="main-font weight-300 font-30 text-black-gray">Please select who you are?</h1>
                  </div>
                  <div data-controller="questionaires-lotr questionaires-ll" class="ques-3-choice d-flex justify-content-around">
                    <div class="status-container d-flex flex-column align-items-center">
                      <h1 class="mb-3 ques-3-icon">⛺️</h1>
                      <div data-questionaires-ll-target="boo" data-questionaires-lotr-target="ques" id="3" data-questionaires-ll-status-param="I'm a local" data-action="click->questionaires-lotr#status click->questionaires-ll#fire" data-questionaires-lotr-status-param="local" class="ques-3-ans">
                        <h5 class="mb-0"><%= f.label :status, "I'm a local", class: "mx-3 main-font weight-300 font-18 text-black-gray mb-0" %></h5>
                      </div>
                    </div>
                    <div class="or-text d-flex justify-content-center pt-5">
                      <h5 class="weight-300 main-font text-black-gray font-18">or</h5>
                    </div>
                    <div class="status-container d-flex flex-column align-items-center">
                      <h1 class="mb-3 ques-3-icon">🚀</h1>
                      <div data-questionaires-ll-target="boo" data-questionaires-lotr-target="ques" id="1" data-questionaires-ll-status-param="I'm a traveller" data-action="click->questionaires-lotr#status click->questionaires-ll#fire" data-questionaires-lotr-status-param="traveller" class="ques-3-ans">
                        <h5 class="mb-0"><%= f.label :staus, "I'm a traveller", class: "mx-1 main-font weight-300 font-18 text-black-gray mb-0" %></h5>
                      </div>
                    </div>
                  </div>
                  <div class="div-explore">
                    <%= f.submit "Explore", class: "explore-btn main-font weight-400" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <button data-last-slide-target="prev" class="carousel-control-prev round-button-prev prev-btn d-none" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="b1 trami-font button-content" aria-hidden="true">←</span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button data-action="click->last-slide#next" data-last-slide-target="button" class="carousel-control-next round-button-next ques-next-btn" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span data-last-slide-target="sign" class="b1 trami-font button-content" aria-hidden="true">→</span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_useravatar.html.erb
<div class="card d-flex column justify-content-between align-items-center p-2" style="background: transparent; border: transparent;">
  <%= image_tag(user.avatar.picture, alt: user.avatar.personality, class:"rounded-circle mb-3", style:"width: 100px")%>
  <h5 class="mb-2 font-30" ><strong><%= user.username %></strong></h5>
  <p class="mb-2 text-muted text-align-center"><strong><%= (Date.today - user.birthdate).to_i / 365 %></strong> years old <span class="badge bg-secondary" style="background-color: rgba(206, 187, 165, .35)"><%= user.ranking.name %></span></p>
</div>