config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "dashboard", to: "dashboards#show"
  resources :rooms, except: %i[edit destroy] do
    resources :messages, only: :create
  end

  resources :users, only: :show do
    resources :appointments, only: %i[update]
  end

  resources :appointments, only: %i[create update]
  resources :chatrooms, only: :show

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/room.rb
class Room < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :appointments
  # has_many :participants, class_name: 'User', through: :appointments, source: :user, foreign_key: 'user_id'
  belongs_to :user
  belongs_to :activity
  geocoded_by :address

  GENDER_OPTIONS = ["men", "women", "no preference"]
  validates :description, :gender, :date, :max_part, :min_part, :language, presence: true
  # validates :description, length: { in: (50...400) }
  validates :min_age, numericality: { greater_than_or_equal_to: 18, message: "must be at least 18" }
  # validates :max_age, numericality: { less_than: 99, message: "must be bellow 99" }
  # max age must be > min age
  validates_comparison_of :max_age, greater_than: :min_age
  validates :gender, inclusion: { in: GENDER_OPTIONS }
  # validate :date_must_be_in_the_future
  validates :min_part, numericality: { greater_than_or_equal_to: 2, message: "must be at least 2" }
  # validates :max_part, numericality: { less_than: 10, message: "must be bellow 10 " }
  # max_part must be > min part
  # validates_comparison_of :max_part, greater_or_equal_than: :min_part
  # participants < max_part
  # TODO: validates_comparison_of :max_part, greater_or_equal_than: :participants
  after_validation :geocode, if: :will_save_change_to_address?


  private

  def date_must_be_in_the_future
    errors.add(:date, "can't be in the past") if date < Date.today
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    possible_moods = ["relax", "dreamy", "energetic", "neutral", "social", "competitive", "adventurous", "chillin", "creative", "intellectual", "exploratory", "mindful"]
    cap = possible_moods.each(&:capitalize)
    @address_params = params[:address].present?
    if @address_params
      if params[cap].present?
        @selected_mood_names = params.keys.map(&:downcase).select { |key| possible_moods.include?(key) }
        Rails.logger.debug "Selected mood names: #{@selected_mood_names.inspect}"

        @rooms = Room.joins(activity: :mood).where(moods: { name: @selected_mood_names })
        if params[:date].present?
          dates = params[:date].split(" to ", 2)
          @date_from = DateTime.parse(dates[0])
          @date_to = DateTime.parse(dates[1])
          @rooms = @rooms.where("date >= ? AND date <= ?", @date_from, @date_to)
        else
          params[:date] = ''
          @rooms = @rooms.where(date: params[:date])
        end
      else
        if params[:date].present?
          dates = params[:date].split(" to ", 2)
          @date_from = DateTime.parse(dates[0])
          @date_to = DateTime.parse(dates[1])
          @rooms = Room.where("date >= ? AND date <= ?", @date_from, @date_to)
        else
          params[:date] = ''
          @rooms = Room.where(date: params[:date])
        end
      end
      address = params[:address]
      @rooms = @rooms.where("address LIKE ?", "%#{address}%")
    else
      @rooms = Room.all
    end

    @markers = @rooms.geocoded.map do |room|
      {
        lat: room.latitude,
        lng: room.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {room: room}),
        marker_html: render_to_string(partial: "marker",locals: {room: room}),
      }
    end
  end

  def new
    @room = Room.new
    @all_activities = []
    Activity.all.each do |activity|
      @all_activities << activity.title.capitalize
    end
    @gender_options = ["Men", "Women", "No Preference", "other"]
    @languages_options = ["en", "de", "fr", "sp", "it", "other"]
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    @room.activity_id = params[:room][:activity_id]
    @room.save
    @appointment = Appointment.new(user: current_user, room: @room, ownership: true, presence: true, status: 1)
    @appointment.save
    redirect_to room_path(@room)
  end

  def update
    @room = @room = Room.find(params[:id])
    @room.update(room_params)
    @room.save!
    redirect_to room_path(@room)
  end

  def show
    @room = Room.find(params[:id])
    @chatroom = Chatroom.find_by(room: @room)
    @message = Message.new
    @user_type = @room.appointments
    creation_instant = (Time.now - @room.created_at)
    if creation_instant < 60
      @creation_date = creation_instant.to_i
      @unit = "seconds"
    elsif creation_instant >= 60 && creation_instant < (60 * 60)
      @creation_date = (creation_instant / 60).to_i
      @unit = "minutes"
    elsif creation_instant >= (60 * 60) && creation_instant < (60 * 60 * 24)
      @creation_date = (creation_instant / (60 * 60)).to_i
      @unit = "hours"
    else
      @creation_date = (creation_instant / (60 * 60 * 24)).to_i
      @unit = "days"
    end
    if current_user
      @currentuser_rooms = []
      current_user.appointments.each do |appointment|
        @currentuser_rooms << appointment.room
      end
    end
  end

  private

  def room_params
    params.require(:room).permit(:title, :description, :gender, :date, :max_part, :min_part, :address, :language, :min_age, :max_age, :latitutde, :longitude)
  end
end

app/views/rooms/_chatroom.html.erb
<% if @room.user == current_user %>
    <% message_class = "my-message" %>
  <% else %>
    <% message_class = "other-message" %>
<% end %>

<div class="container chatroom"
     data-controller="chatroom-subscription"
     data-chatroom-subscription-chatroom-id-value="<%= @room.id %>"
     data-chatroom-subscription-user-id-value="<%= current_user.id %>">
  <h1>Chatroom</h1>
    <div>
    </div>
    <div class="messages" data-chatroom-subscription-target="messages">
      <% @chatroom.messages.each do |message| %>
          <%= render "messages/message", message: message %>
      <% end %>
      </div>
  <%= simple_form_for [@room, @message],
  html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
%>
  <%= f.input :content,
    label: false,
    placeholder: "Message ##{@room.title}",
    wrapper_html: {class: "flex-grow-1"}
  %>
  <%= f.submit "Send", class: "btn btn-outline-secondary", style:"height: 38px;"%>
  <% end %>
</div>

app/views/rooms/_form.html.erb
<%# <%= f.input :address,
  input_html: {data: input_html: {data: {"..."}, class: "d-none"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%> 

app/views/rooms/_info_window.html.erb
<%# <h2><%= room.name</h2> %>
<%# <p><%= room.address %>

app/views/rooms/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>
<div class="badge rounded-pill bg-primary fs-6">
  <%= room.title %>
</div>

app/views/rooms/_newdescriptionform.html.erb
    <%= simple_form_for @room do |f| %>
      <%= f.input :title, placeholder: "How do you want to call this event?"%>
      <%= f.input :description, placeholder: "Please describe it so other Tramiers get interested", as: :text %>
      <%= f.select :language, @languages_options %>
      <%= f.select :gender, @gender_options %>
      <%= f.input :date, as: :datetime, html5: true %>

      <%= f.select :activity, @all_activities %>
      <%= f.button :submit %>
    <% end %>

app/views/rooms/_participantcard.html.erb
<div class="col" style= "border-color: <%= user.mood.color %>">
  
  <div>
  </div>
</div>

app/views/rooms/_participantcardlight.html.erb
<div class="avatar-decline-accept">
  <div class="small-avatar-container">
    <!-- Modal Trigger Button -->
    <button type="button" class="avatar-image" style="border: none; background: none; padding: 0; margin: 0;" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title= <%= user.description %> >
      <!-- Ensure the image_tag helper generates the correct image source -->
      <!-- Replace `user.avatar.picture` with the actual image source -->
      <%= image_tag(user.avatar.picture, alt: user.avatar.personality, class: "avatar w-100", style: "border:#{user.mood.color}  5px solid;")%>
    </button>

    <!-- Avatar Text -->
    <div class="avatar-text">
      <h3><%= user.username %></h3>
    </div>
    <!-- Avatar Gender -->
    <div class="avatar-gender">
      <!-- Ensure the correct gender image is displayed -->
      <%= image_tag("#{user.gender}.png", alt: user.avatar.personality, class: "gender-avatar")%>
    </div>
  </div>
  <% if user == @room.user %>
    <div class="button-container">
      <div class="creator-pin">Creator</div>
    </div>
  <% end %>
</div>

app/views/rooms/_requestcard.html.erb
<div class="avatar-decline-accept">
    <div class="small-avatar-container">
        <div class="avatar-image">
          <%= image_tag(appointment.user.avatar.picture, alt: appointment.user.avatar.personality, class: "avatar w-100", style: "border:#{appointment.user.mood.color}  5px solid;filter: grayscale(100%); ")%>
        </div>
        <div class="avatar-text">
          <h3 style="filter: grayscale(100%);"><%= appointment.user.username %></h3>
        </div>
        <div class="avatar-gender ">
          <%= image_tag("#{appointment.user.gender}.png", alt: appointment.user.avatar.personality, class: "gender-avatar")%>
        </div>
    </div>
    <div class="button-container">
      <%= form_with(url: appointment_path(appointment), method: :patch) do |f| %>
        <%= f.hidden_field :status, value: 1 %>
        <%= f.submit "Accept", class: "accept-button" %>
      <% end %>
      <%= form_with(url: appointment_path(appointment), method: :patch) do |f| %>
      <%= f.hidden_field :status, value: 3 %>
      <%= f.submit "Decline", class: "decline-button" %>
      <% end %>
    </div>
</div>

app/views/rooms/_roomcard.html.erb
<% if @rooms.present? && @address_params %>
  <div class="r-main d-flex justify-content-center">
    <div class="r-wrap pt-3">
      <% @rooms.each do |room| %>
        <%= link_to room_path(room), class: "text-decoration-none" do %>
          <div class="d-flex justify-content-center">
            <div class="r-card d-flex flex-column">
              <div class="<%= room.activity.mood.name %>-img img-saturate">
                <div class="r-title-box d-flex flex-column justify-content-center align-items-center">
                  <h5 class="r-title text-center"><%= room.title %></h5>
                  <div class="r-hover d-flex flex-column align-items-center">
                  </div>
                </div>
              </div>
              <div class="r-detail px-3 d-flex justify-content-around">
                <div class="d-flex align-items-center">
                  <div class=""><%= image_tag("#{room.gender}.png", alt: room.gender, class: "r-gender-img")%></div>
                </div>
                <div class="d-flex align-items-center">
                  <p class="r-age mb-0 px-2 text-black-gray">Age</p>
                  <p class="r-age-box mb-0 text-black-gray"><%= room.min_age %> - <%= room.max_age %></p>
                </div>
                <div class="d-flex align-items-center">
                  <div class=""><%= image_tag("calendar.png", alt: "calendar", class: "r-calendar grayscale contrast brightness")%></div>
                  <p class="r-date-time mb-0 px-1 text-black-gray"><%= room.date.strftime('%d %b %y')%></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% elsif @rooms.present? == false %>
  <div class="r-wrap d-flex px-5 pt-4 justify-content-start"><h5 class="main-font mb-0 weight-300">Sorry, there's no rooms available on your search.</h5></div>
<% else %>
  <div class="r-main d-flex justify-content-center">
    <div class="r-wrap pt-3">
      <% @rooms.each do |room| %>
        <%= link_to room_path(room), class: "text-decoration-none" do %>
          <div class="d-flex justify-content-center">
            <div class="r-card d-flex flex-column">
              <div class="<%= room.activity.mood.name %>-img img-saturate">
                <div class="r-title-box d-flex flex-column justify-content-center align-items-center">
                  <h5 class="r-title text-center"><%= room.title %></h5>
                  <div class="r-hover d-flex flex-column align-items-center">
                  </div>
                </div>
              </div>
              <div class="r-detail px-3 d-flex justify-content-around">
                <div class="d-flex align-items-center">
                  <div class=""><%= image_tag("#{room.gender}.png", alt: room.gender, class: "r-gender-img")%></div>
                </div>
                <div class="d-flex align-items-center">
                  <p class="r-age mb-0 px-2 text-black-gray">Age</p>
                  <p class="r-age-box mb-0 text-black-gray"><%= room.min_age %> - <%= room.max_age %></p>
                </div>
                <div class="d-flex align-items-center">
                  <div class=""><%= image_tag("calendar.png", alt: "calendar", class: "r-calendar grayscale contrast brightness")%></div>
                  <p class="r-date-time mb-0 px-1 text-black-gray"><%= room.date.strftime('%d %b %y')%></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/rooms/_roominfos.html.erb
<div class="row justify-content-between w-100 align-items-center" style="border-top: grey solid; padding: 5px;border-bottom: grey solid; padding: 5px;">
            <%= image_tag("#{@room.gender}.png", alt: @room.gender, class: "image-show")%>
            <div class= "col d-flex align-items-center">Age <div class="r-age-box mb-0 mx-2 text-black-gray"><%= @room.min_age %> - <%= @room.max_age %></div></div>
            <div class= "col">&#128100; <strong><%= @room.min_part %> to <%= @room.max_part %> </strong>participants</div>
            <div class= "col">&#129304; <strong><%= @room.participants %></strong> tramiers in the room</div>
            <div class= "col"> Created <strong><%= @creation_date %> <%= @unit %></strong> ago </div>
</div>

app/views/rooms/index.html.erb
<div id="index-main">
  <div class="d-flex">
    <%= link_to "←", 'javascript:history.back()', class: "mt-2 r-back-btn" %>
    <%= link_to "+", new_room_path, class: "mt-2 r-new-btn" %>
    <div class="left pt-2 d-flex flex-column align-items-start">
      <div class="room-search-bar">
        <%= form_with url: rooms_path, method: :get do |f| %>
          <%= f.text_field :address, placeholder: "location", class: "rr-location main-font" %>
          <%= f.text_field :date, data: { controller: "flatpickr" }, placeholder: "from - to", class: "date r-date-1 main-font"%>
          <%= f.submit "search", class: "r-search-btn main-font" %>
        <% end %>
      </div>
      <% if @address_params && @rooms.present? %>
        <h1 class="px-5 main-font weight-300 font-25  mx-4 mt-2 text-black-gray">Activities available through your search</h1>
      <% elsif @rooms.present? == false %>
        <h1 class="px-5 main-font weight-300 font-25  mx-4 mt-2 text-black-gray">Activities available through your search</h1>
      <% else %>
        <h1 class="px-5 main-font weight-300 font-25  mx-4 mt-2 text-black-gray">All activities available in Trami featured cities</h1>
      <% end %>
      <div class="half-bottom">
        <div class="all-rooms-container">
          <div class="all-rooms d-flex justify-content-center">
            <%= render 'roomcard' %>
          </div>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-end rooms-map">
      <div style="width: 100%; height: 84.5vh;" data-controller="map" data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="padding-b">
  <div class="main-container-form">
    <%= link_to '←', 'javascript:history.back()', class: "back-search-btn" %>
    <div class="new-form-container">
      <h1 class="fadein-1 d-flex justify-content-center text-black-gray font-60 pb-3"> Create a new room! </h1>
      <div class="fadein-2">
        <h3 class="d-flex justify-content-center main-font weight-300 text-black-gray mt-3 font-22 mb-3"> How do you feel for this event?</h3>
        <div class ="container" data-controller="toggle-new">
          <div class="d-flex flex-column align-items-center text-center px-5 mx-5">
            <div class="d-flex">
              <% Mood.all.first(6).each do |mood| %>
                <div data-controller="mood-color" data-toggle-new-target="reset" data-action="click->toggle-new#fire mouseover->mood-color#displayColor mouseout->mood-color#resetColor" data-mood-target="moodName" class="mood-button d-flex justify-content-center align-items-center mx-1" data-color="<%= mood.color %>"> <%= mood.name.capitalize %> </div>
              <% end %>
            </div>
            <div class="d-flex">
              <% Mood.all.last(6).each do |mood| %>
                <div data-controller="mood-color" data-toggle-new-target="reset" data-action="click->toggle-new#fire mouseover->mood-color#displayColor mouseout->mood-color#resetColor" data-mood-target="moodName" class="mood-button d-flex justify-content-center align-items-center mx-1" data-color="<%= mood.color %>"> <%= mood.name.capitalize %> </div>
              <% end %>
            </div>
          </div>
          <div data-toggle-new-target="togglableElement" class="d-none mt-5 px-5">
            <%= simple_form_for @room do |f| %>
            <%= f.error_notification %>

            <%= f.input :title, required: true %>
            <%= f.input :description, required: true %>

            <%= f.input :gender, collection: Room::GENDER_OPTIONS, prompt: "Select Gender", required: true %>

            <%= f.input :date, as: :date, required: true,
                        input_html: { min: Date.today.to_s } %>
            <br>
            <br>
            <%= f.input :min_part, required: true, input_html: { min: 2 } %>
            <%= f.input :max_part, required: true, input_html: { min: 2 } %>

            <%= f.input :language, required: true %>

            <%= f.input :min_age, required: true, input_html: { min: 18, max: 99 } %>
            <%= f.input :max_age, required: true, input_html: { min: 18, max: 99 } %>

            <%= f.input :activity_id, collection: Activity.all, label_method: :title, value_method: :id, prompt: "Select Activity", required: true %>
            <br>
            <button class="start-button">
              <%= f.button :submit, "Create Room", class:"button-content" %>
            </button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="main-container d-flex justify-content-center" style="background-color: <%= @room.activity.mood.color%>;  background-image: linear-gradient(rgba(0, 0, 0, .1) .1em, transparent .1em), linear-gradient(90deg, rgba(0, 0, 0, .1) .1em, transparent .1em);
    background-size: 2em 2em;">
    <div class="room-show-container d-flex flex-column" style="background-color: white;">
      <div class ="row">
        <div class = "col-8">
          <h3 class="main-font weight-500 font-22" style="border-bottom: grey solid; padding: 5px;"> <%= @room.title %> <div class="badge bg-success" style="background-color: #9BC88B;"><%= @room.date.strftime('%d %B %y') %></div></h3>
          <p style="margin-top: 15px"> <%= @room.description.capitalize %></p>
          <p>&#128204; <%= @room.address %></p>
          <% if current_user == @room.user %>
            <button  class="round-button"  style="height: auto; width: auto; background-color: rgb(62, 62, 62);" > change the address </button>
          <% end %>
          </div>
          <div class = "col-4">
            <%= render "shared/useravatar", user: @room.user %>
          </div>
          <div class = "informations-banner">
            <%= render "roominfos", room: @room %>
          </div>
      </div>
      <div>
      <% if current_user &&  @currentuser_rooms.include?(@room)%>
        <% if @room.appointments.find_by(user: current_user).status == 1%>
          <div class="row" data-controller="show-page-button">
            <p>This room has <strong style="font-size: 20px"><%= @room.participants - 1 %></strong> other <button class="round-button" data-action="click->show-page-button#toggleVisibility" data-show-page-button-target="toggleButton" style="height: auto; width: auto; background-color: rgb(62, 62, 62); margin: 2px;">participants</button></p>
            <div class="d-none d-flex" data-show-page-button-target="allParticipants">
              <div data-controller="upcomingrooms-swiper">
                <% @room.appointments.reject{ |appointment| appointment.user == current_user || appointment.status != 1 }.each do |appointment| %>
                  <%= render "participantcardlight", user: appointment.user %>
                <% end %>
                <% if @room.user == current_user %>
                  <% @room.appointments.reject{ |appointment| appointment.user == @room.user || appointment.status != 0 || appointment.status == 3 }.each do |appointment| %>
                  <%= render "requestcard", appointment: appointment %>
                <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <%= render "chatroom", room: @room, chatroom: @chatroom, messages: @messages %>
    <% elsif @room.appointments.find_by(user: current_user).status == 0 %>
          <h3 class="text-center" style="padding-top:60px;"> You're participation is still <strong>pending</strong>... Wait a bit ....</h3>
      <% end %>
      <% elsif current_user && @room.participants < @room.max_part %>
      <div style="text-align: center;">
        <%= form_with url: appointments_path, method: :post do |f| %>
            <%= f.hidden_field :status, value: 0 %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.hidden_field :presence, value: false%>
            <%= f.hidden_field :ownership, value: false %>
            <%= f.submit "Join this amazing event!", class: "explore-btn" %>
        <% end %>
        </div>
      <% elsif  @room.participants >= @room.max_part %>
        <h3 class="text-center" style="background-color = orange;"> This room is <strong>full</strong>!! Sorry ...</h3>
      <% else %>
      <h3 class="text-center" style="padding-top: 60px ;"> You have to <strong>Sign Up or Login</strong> to access more details!! </h3>
    <% end  %>
    </div>
  </div>